### ISSUE TITLE
emerge  sys-kernel/novena-sources-4.7.2-r1::novena fails

### ISSUE THREAD

**Issue by mike01** [sakaki-/novena-overlay#1]
When emerging " sys-kernel/novena-sources-4.7.2-r1::novena" the download fails:

>>> Emerging (1 of 1) sys-kernel/novena-sources-4.7.2-r1::novena
 * linux-4.7.tar.xz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                    [ ok ]
>>> Downloading 'http://distfiles.gentoo.org/distfiles/genpatches-4.7-3.base.tar.xz'
--2016-12-07 01:38:49--  http://distfiles.gentoo.org/distfiles/genpatches-4.7-3.base.tar.xz
Resolving distfiles.gentoo.org... 156.56.247.195, 216.165.129.135, 137.226.34.46, ...
Connecting to distfiles.gentoo.org|156.56.247.195|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-12-07 01:38:49 ERROR 404: Not Found.

>>> Downloading 'http://ftp.halifax.rwth-aachen.de/gentoo/distfiles/genpatches-4.7-3.base.tar.xz'
--2016-12-07 01:38:49--  http://ftp.halifax.rwth-aachen.de/gentoo/distfiles/genpatches-4.7-3.base.tar.xz
Resolving ftp.halifax.rwth-aachen.de... 137.226.34.46, 2a00:8a60:e012:a00::21
Connecting to ftp.halifax.rwth-aachen.de|137.226.34.46|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-12-07 01:38:49 ERROR 404: Not Found.

>>> Downloading 'http://gentoo.osuosl.org/distfiles/genpatches-4.7-3.base.tar.xz'
--2016-12-07 01:38:49--  http://gentoo.osuosl.org/distfiles/genpatches-4.7-3.base.tar.xz
Resolving gentoo.osuosl.org... 140.211.166.134, 64.50.236.52, 64.50.233.100, ...
Connecting to gentoo.osuosl.org|140.211.166.134|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-12-07 01:38:50 ERROR 404: Not Found.

>>> Downloading 'http://gentoo-distfiles.mirrors.tds.net/distfiles/genpatches-4.7-3.base.tar.xz'
--2016-12-07 01:38:50--  http://gentoo-distfiles.mirrors.tds.net/distfiles/genpatches-4.7-3.base.tar.xz
Resolving gentoo-distfiles.mirrors.tds.net... 216.165.129.135
Connecting to gentoo-distfiles.mirrors.tds.net|216.165.129.135|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-12-07 01:38:50 ERROR 404: Not Found.

>>> Downloading 'http://gentoo.ussg.indiana.edu/distfiles/genpatches-4.7-3.base.tar.xz'
--2016-12-07 01:38:50--  http://gentoo.ussg.indiana.edu/distfiles/genpatches-4.7-3.base.tar.xz
Resolving gentoo.ussg.indiana.edu... 156.56.247.195
Connecting to gentoo.ussg.indiana.edu|156.56.247.195|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-12-07 01:38:51 ERROR 404: Not Found.

!!! Couldn't download 'genpatches-4.7-3.base.tar.xz'. Aborting.
 * Fetch failed for 'sys-kernel/novena-sources-4.7.2-r1', Log file:
 *  '/var/tmp/portage/sys-kernel/novena-sources-4.7.2-r1/temp/build.log'

**Comment by sakaki-** [comment]
Ah yes, sorry about that. I'll need to bump the version of genpatches cited in the ebuild, test, and re-release (the 4.7 v3 set has been dropped from the Gentoo archives).
In the meantime, if it helps, I've included a zip of the necessary files: 
[genpatches.zip](https://github.com/sakaki-/novena-overlay/files/646779/genpatches.zip). If you unzip this and then place the enclosed `genpatches-4.7-3.base.tar.xz` and  `genpatches-4.7-3.extras.tar.xz` into your `/usr/portage/distfiles` directory, I think you should be able to build.
hth, sakaki

**Comment by mike01** [comment]
Thanks, that works like a charm.

**Comment by sakaki-** [comment]
New revisions of novena-sources and novena_hardened-sources for 4.7.2 now pushed. These fetch their genpatches from [mpagano's archive](https://dev.gentoo.org/~mpagano/genpatches/tarballs/) on dev.gentoo.org, which should be more stable.
